// ui/src/vue/App.vue
<!-- Vue port of src/App.tsx. Owns global state: conversation list,
     current/viewed conversation, drawer, command palette + modals, ephemeral
     terminals, the global SSE stream, URL/slug sync, page title, and global
     keyboard shortcuts. Renders ConversationDrawer, ChatInterface,
     CommandPalette and the modals.

     Worker pool: the React App wrapped everything in @pierre/diffs
     WorkerPoolContextProvider. PatchTool.vue uses the @pierre/diffs SSR
     (synchronous) API and needs no worker pool, so no provider is rendered
     here. -->
<template>
  <!-- Loading gate -->
  <div v-if="loading && conversations.length === 0" class="loading-container">
    <div class="loading-content">
      <div class="spinner" style="margin: 0 auto 1rem" />
      <p class="text-secondary">{{ t("loading") }}</p>
    </div>
  </div>

  <div v-else-if="error && conversations.length === 0" class="error-container">
    <div class="error-content">
      <p class="error-message" style="margin-bottom: 1rem">{{ error }}</p>
      <button class="btn-primary" @click="loadConversations">{{ t("retry") }}</button>
    </div>
  </div>

  <template v-else>
    <div v-if="banner" class="top-banner" :title="banner">{{ banner }}</div>
    <div class="app-container">
      <ConversationDrawer
        :is-open="drawerOpen"
        :is-collapsed="drawerCollapsed"
        :conversations="conversations"
        :current-conversation-id="currentConversationId"
        :viewed-conversation="viewedConversation"
        :show-active-trigger="showActiveTrigger"
        @close="drawerOpen = false"
        @toggle-collapse="toggleDrawerCollapsed"
        @select-conversation="selectConversation"
        @new-conversation="startNewConversation"
        @archived="handleConversationArchived"
        @unarchived="handleConversationUnarchived"
        @renamed="handleConversationRenamed"
        @use-in-composer="handleUseInComposer"
      />

      <div class="main-content">
        <ChatInterface
          :insert-composer-trigger="composerInsert"
          :conversation-id="currentConversationId"
          :stream-status="streamStatus"
          :reconnect-nonce="reconnectNonce"
          :on-open-drawer="() => (drawerOpen = true)"
          :on-new-conversation="startNewConversation"
          :on-select-conversation="selectConversation"
          :on-archive-conversation="archiveFromChat"
          :current-conversation="currentConversation"
          :on-conversation-update="updateConversation"
          :on-first-message="handleFirstMessage"
          :on-draft-created="onDraftCreated"
          :on-distill-new-generation="handleDistillNewGeneration"
          :most-recent-cwd="mostRecentCwd"
          :is-drawer-collapsed="drawerCollapsed"
          :on-toggle-drawer-collapse="toggleDrawerCollapsed"
          :open-diff-viewer-trigger="diffViewerTrigger"
          :open-git-graph-trigger="gitGraphTrigger"
          :open-terminal-trigger="terminalTrigger"
          :models-refresh-trigger="modelsRefreshTrigger"
          :cwd-sync-trigger="cwdSyncTrigger"
          :on-open-models-modal="() => (modelsModalOpen = true)"
          :ephemeral-terminals="ephemeralTerminals"
          :set-ephemeral-terminals="setEphemeralTerminals"
          :on-terminal-attached="handleTerminalAttached"
          :on-terminal-close="handleTerminalClose"
          :navigate-user-message-trigger="navigateUserMessageTrigger"
          :on-conversation-unarchived="handleConversationUnarchived"
        />
      </div>

      <CommandPalette
        :is-open="commandPaletteOpen"
        :conversations="topLevelConversations"
        :current-conversation="currentConversation || null"
        :has-cwd="commandPaletteHasCwd"
        @close="onCommandPaletteClose"
        @new-conversation="
          () => {
            startNewConversation();
            commandPaletteOpen = false;
          }
        "
        @new-conversation-with-cwd="
          (cwd) => {
            startNewConversationWithCwd(cwd);
            commandPaletteOpen = false;
          }
        "
        @set-conversation-cwd="
          (cwd) => {
            setConversationCwd(cwd);
            commandPaletteOpen = false;
          }
        "
        @select-conversation="
          (c) => {
            selectConversation(c);
            commandPaletteOpen = false;
          }
        "
        @archive-conversation="archiveFromPalette"
        @open-diff-viewer="
          () => {
            diffViewerTrigger++;
            commandPaletteOpen = false;
          }
        "
        @open-git-graph="
          () => {
            gitGraphTrigger++;
            commandPaletteOpen = false;
          }
        "
        @open-terminal="
          () => {
            terminalTrigger++;
            commandPaletteOpen = false;
          }
        "
        @open-models-modal="
          () => {
            modelsModalOpen = true;
            commandPaletteOpen = false;
          }
        "
        @open-notifications-modal="
          () => {
            notificationsModalOpen = true;
            commandPaletteOpen = false;
          }
        "
        @open-feature-flags-modal="
          () => {
            featureFlagsModalOpen = true;
            commandPaletteOpen = false;
          }
        "
        @next-conversation="navigateToNextConversation"
        @previous-conversation="navigateToPreviousConversation"
        @next-user-message="navigateToNextUserMessage"
        @previous-user-message="navigateToPreviousUserMessage"
      />

      <ModelsModal
        :is-open="modelsModalOpen"
        @close="
          () => {
            modelsModalOpen = false;
            focusMessageInputIfUnfocused();
          }
        "
        @models-changed="modelsRefreshTrigger++"
      />

      <NotificationsModal
        :is-open="notificationsModalOpen"
        @close="
          () => {
            notificationsModalOpen = false;
            focusMessageInputIfUnfocused();
          }
        "
      />

      <FeatureFlagsModal
        :is-open="featureFlagsModalOpen"
        @close="
          () => {
            featureFlagsModalOpen = false;
            focusMessageInputIfUnfocused();
          }
        "
      />

      <div v-if="drawerOpen" class="backdrop hide-on-desktop" @click="drawerOpen = false" />
    </div>
  </template>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import ChatInterface from "./components/ChatInterface.vue";
import ConversationDrawer from "./components/ConversationDrawer.vue";
import CommandPalette from "./components/CommandPalette.vue";
import ModelsModal from "./components/ModelsModal.vue";
import NotificationsModal from "./components/NotificationsModal.vue";
import FeatureFlagsModal from "./components/FeatureFlagsModal.vue";
import type { EphemeralTerminal } from "./components/terminalTypes";
import { focusMessageInputIfUnfocused } from "../utils/focusMessageInput";
import {
  type Conversation,
  type ConversationWithState,
  type ConversationListPatchEvent,
} from "../types";
import { api } from "../services/api";
import { messageStore } from "../services/messageStore";
import {
  reduceConversationListPatch,
  type ConversationListState,
} from "../services/conversationListStream";
import { connectGlobalStream, type StreamStatus } from "../services/globalStream";
import { handleNotificationEvent } from "../services/notifications";
import { loadCachedDraft } from "../services/draftCache";
import { useI18n } from "./composables/i18n";

const { t } = useI18n();

// ---- URL/slug helpers ----
function isGeneratedId(slug: string | null): boolean {
  if (!slug) return true;
  return /^c[a-z0-9]+$/i.test(slug);
}
function getSlugFromPath(): string | null {
  const path = window.location.pathname;
  if (path.startsWith("/c/")) {
    const slug = path.slice(3);
    if (slug) return slug;
  }
  return null;
}
function isNewPath(): boolean {
  return window.location.pathname === "/new";
}

// A brand-new-conversation draft composed offline never reaches the server
// (createDraft fails), so it survives only in localStorage under the "new"
// slot. On reopen we land on "/" and would otherwise auto-select the most
// recent conversation, orphaning that text. Detect a pending non-empty cached
// draft so startup can keep the user in the new-conversation view instead.
function hasPendingNewDraft(): boolean {
  return !!loadCachedDraft(null)?.value.trim();
}

// Captured BEFORE render so URL-updating effects don't clobber it.
const initialSlugFromUrl = getSlugFromPath();
const initialIsNew = isNewPath() || (!getSlugFromPath() && hasPendingNewDraft());

function updateUrlWithSlug(conversation: Conversation | undefined) {
  const currentSlug = getSlugFromPath();
  let newSlug: string | null = null;
  if (conversation?.slug && !isGeneratedId(conversation.slug)) {
    newSlug = conversation.slug;
  } else if (conversation?.is_draft) {
    newSlug = conversation.conversation_id;
  }
  if (currentSlug !== newSlug) {
    if (newSlug) window.history.replaceState({}, "", `/c/${newSlug}`);
    else window.history.replaceState({}, "", "/");
  }
}

function updatePageTitle(conversation: Conversation | undefined) {
  const hostname = window.__SHELLEY_INIT__?.hostname;
  const parts: string[] = [];
  if (conversation?.slug && !isGeneratedId(conversation.slug)) parts.push(conversation.slug);
  if (hostname) parts.push(hostname);
  parts.push("Shelley Agent");
  document.title = parts.join(" - ");
}

const banner = window.__SHELLEY_INIT__?.banner;

// ---- state ----
const conversations = ref<ConversationWithState[]>([]);
const currentConversationId = ref<string | null>(null);
const viewedConversation = ref<Conversation | null>(null);
const drawerOpen = ref(false);
const drawerCollapsed = ref(false);
// Text to insert into the composer when a Library item's "Use this" is clicked.
// The nonce makes repeated inserts of the same text distinct so ChatInterface's
// watcher fires each time.
const composerInsert = ref<{ text: string; nonce: number } | undefined>(undefined);
let composerInsertNonce = 0;
function handleUseInComposer(text: string) {
  composerInsert.value = { text, nonce: ++composerInsertNonce };
  drawerOpen.value = false;
}
const commandPaletteOpen = ref(false);
const diffViewerTrigger = ref(0);
const gitGraphTrigger = ref(0);
const terminalTrigger = ref(0);
const modelsModalOpen = ref(false);
const notificationsModalOpen = ref(false);
const featureFlagsModalOpen = ref(false);
const modelsRefreshTrigger = ref(0);
const cwdSyncTrigger = ref(0);
const navigateUserMessageTrigger = ref(0);
const loading = ref(true);
const error = ref<string | null>(null);
const ephemeralTerminals = ref<EphemeralTerminal[]>([]);
const streamStatus = ref<StreamStatus>("connected");
const reconnectNonce = ref(0);
const showActiveTrigger = ref(0);

// ---- non-reactive refs ----
let initialSlugResolved = false;
let conversationListHash: string | null = null;
let globalStreamHandle: { forceReconnect: () => void; close: () => void } | null = null;

// setEphemeralTerminals supports both array and updater-function forms (parity
// with React's setState) so ChatInterface can call it like the React prop.
function setEphemeralTerminals(
  next: EphemeralTerminal[] | ((prev: EphemeralTerminal[]) => EphemeralTerminal[]),
) {
  ephemeralTerminals.value = typeof next === "function" ? next(ephemeralTerminals.value) : next;
}

function handleTerminalAttached(id: string, termId: string) {
  setEphemeralTerminals((prev) => prev.map((tm) => (tm.id === id ? { ...tm, termId } : tm)));
}

function handleTerminalClose(id: string) {
  setEphemeralTerminals((prev) => {
    const tm = prev.find((x) => x.id === id);
    if (tm && tm.termId) {
      fetch(`/api/terminals/${encodeURIComponent(tm.termId)}`, { method: "DELETE" }).catch((err) =>
        console.warn("failed to delete terminal:", err),
      );
    }
    return prev.filter((x) => x.id !== id);
  });
}

// ---- derived ----
const topLevelConversations = computed(() =>
  conversations.value.filter((c) => !c.parent_conversation_id),
);

const currentConversation = computed<ConversationWithState | undefined>(() => {
  const found = conversations.value.find(
    (conv) => conv.conversation_id === currentConversationId.value,
  );
  if (found) return found;
  if (viewedConversation.value?.conversation_id === currentConversationId.value) {
    return {
      ...viewedConversation.value,
      working: false,
      subagent_count: 0,
      max_sequence_id: 0,
    } as ConversationWithState;
  }
  return undefined;
});

const mostRecentCwd = computed(
  () =>
    currentConversation.value?.cwd ||
    (topLevelConversations.value.length > 0 ? topLevelConversations.value[0].cwd : null),
);

const commandPaletteHasCwd = computed(
  () =>
    !!(
      currentConversation.value?.cwd ||
      mostRecentCwd.value ||
      localStorage.getItem("shelley_selected_cwd") ||
      window.__SHELLEY_INIT__?.default_cwd
    ),
);

// ---- navigation ----
function navigateToNextConversation() {
  const list = topLevelConversations.value;
  if (list.length === 0) return;
  const currentIndex = list.findIndex((c) => c.conversation_id === currentConversationId.value);
  const nextIndex = currentIndex < 0 ? 0 : Math.min(currentIndex + 1, list.length - 1);
  const next = list[nextIndex];
  currentConversationId.value = next.conversation_id;
  viewedConversation.value = next;
}
function navigateToPreviousConversation() {
  const list = topLevelConversations.value;
  if (list.length === 0) return;
  const currentIndex = list.findIndex((c) => c.conversation_id === currentConversationId.value);
  const prevIndex = currentIndex < 0 ? 0 : Math.max(currentIndex - 1, 0);
  const prev = list[prevIndex];
  currentConversationId.value = prev.conversation_id;
  viewedConversation.value = prev;
}
function navigateToNextUserMessage() {
  navigateUserMessageTrigger.value = Math.abs(navigateUserMessageTrigger.value) + 1;
}
function navigateToPreviousUserMessage() {
  navigateUserMessageTrigger.value = -(Math.abs(navigateUserMessageTrigger.value) + 1);
}

// ---- conversation list patch handling ----
// The conversation list and the hash it was produced under are a single
// coupled value: the patch stream is a strict old_hash->new_hash chain, so a
// patch may only be applied to the exact list its old_hash describes. The
// reactive `conversations` ref is the template's source of truth; we mirror it
// (plus the hash) into listState and only ever advance both together via
// commitListState. This matches the React app's coupled {list, hash} state so
// neither client can apply a patch built against new state onto a stale list.
function listStateNow(): ConversationListState {
  return { list: conversations.value, hash: conversationListHash };
}

function commitListState(next: ConversationListState) {
  conversations.value = next.list;
  conversationListHash = next.hash;
}

function recoverConversationListStream() {
  conversationListHash = null;
  globalStreamHandle?.forceReconnect();
}

function handleConversationListPatch(event: ConversationListPatchEvent) {
  const prev = conversations.value;
  const result = reduceConversationListPatch(listStateNow(), event);
  if (!result.ok) {
    if (result.reason === "hash-mismatch") {
      console.warn("conversation list patch hash mismatch; recovering via reconnect", {
        eventOldHash: result.eventOldHash,
        currentHash: conversationListHash,
      });
    } else {
      console.error(
        "failed to apply conversation list patch; recovering via reconnect",
        result.error,
        { patch: event.patch, prevLen: prev.length },
      );
    }
    recoverConversationListStream();
    return;
  }
  for (const removedId of result.removedIds) {
    void messageStore.delete(removedId);
  }
  for (const conv of result.state.list) {
    messageStore.setMaxSequenceIdKnown(conv.conversation_id, conv.max_sequence_id);
    // Seed from `working` — the list's authoritative working flag, which the
    // drawer indicator also renders — so the status bar and the conversation
    // list (the source of truth) never disagree.
    messageStore.setAgentWorking(conv.conversation_id, conv.working);
  }
  commitListState(result.state);
}

// ---- initial slug resolution ----
async function resolveInitialSlug(convs: Conversation[]): Promise<Conversation | null> {
  if (initialSlugResolved) return null;
  initialSlugResolved = true;
  const urlSlug = initialSlugFromUrl;
  if (!urlSlug) return null;
  const existingConv = convs.find((c) => c.slug === urlSlug || c.conversation_id === urlSlug);
  if (existingConv) return existingConv;
  try {
    const conv = await api.getConversationBySlug(urlSlug);
    if (conv) return conv;
  } catch (err) {
    console.error("Failed to resolve slug:", err);
  }
  window.history.replaceState({}, "", "/");
  return null;
}

async function loadConversations() {
  try {
    loading.value = true;
    error.value = null;
    const snapshot = await api.getConversationsSnapshot();
    for (const conv of snapshot.conversations) {
      messageStore.setMaxSequenceIdKnown(conv.conversation_id, conv.max_sequence_id);
    }
    const activeIds = snapshot.conversations.map((c) => c.conversation_id);
    void messageStore.pruneStale(activeIds, 7 * 24 * 60 * 60 * 1000);
    const streamHash = conversationListHash;
    if (!streamHash) {
      commitListState({ list: snapshot.conversations, hash: snapshot.hash });
    }
    const currentList = streamHash ? conversations.value : snapshot.conversations;
    const topLevel = currentList.filter((c) => !c.parent_conversation_id);

    const slugConv = await resolveInitialSlug(currentList);
    if (slugConv) {
      currentConversationId.value = slugConv.conversation_id;
      viewedConversation.value = slugConv;
    } else if (!initialIsNew && topLevel.length > 0) {
      currentConversationId.value = topLevel[0].conversation_id;
      viewedConversation.value = topLevel[0];
    }
  } catch (err) {
    console.error("Failed to load conversations:", err);
    error.value = "Failed to load conversations. Please refresh the page.";
  } finally {
    loading.value = false;
  }
}

// ---- conversation actions ----
function startNewConversation() {
  if (currentConversation.value?.cwd) {
    localStorage.setItem("shelley_selected_cwd", currentConversation.value.cwd);
  }
  currentConversationId.value = null;
  viewedConversation.value = null;
  window.history.replaceState({}, "", "/new");
  drawerOpen.value = false;
}

function startNewConversationWithCwd(cwd: string) {
  localStorage.setItem("shelley_selected_cwd", cwd);
  currentConversationId.value = null;
  viewedConversation.value = null;
  window.history.replaceState({}, "", "/new");
  drawerOpen.value = false;
  cwdSyncTrigger.value++;
}

function setConversationCwd(cwd: string) {
  localStorage.setItem("shelley_selected_cwd", cwd);
  const conv =
    conversations.value.find((c) => c.conversation_id === currentConversationId.value) ||
    (viewedConversation.value?.conversation_id === currentConversationId.value
      ? viewedConversation.value
      : null);
  if (conv?.is_draft) {
    api.updateDraftCwd(conv.conversation_id, cwd).catch((err) => {
      console.debug("Could not persist draft cwd (likely already promoted):", err);
    });
  }
  cwdSyncTrigger.value++;
}

function selectConversation(conversation: Conversation) {
  currentConversationId.value = conversation.conversation_id;
  viewedConversation.value = conversation;
  drawerOpen.value = false;
}

function toggleDrawerCollapsed() {
  drawerCollapsed.value = !drawerCollapsed.value;
}

function updateConversation(updatedConversation: Conversation) {
  if (updatedConversation.conversation_id === currentConversationId.value) {
    viewedConversation.value = updatedConversation;
  }
}

function handleConversationArchived(
  conversationId: string,
  nextConversation?: Conversation | null,
) {
  void messageStore.delete(conversationId);
  if (currentConversationId.value === conversationId) {
    if (nextConversation && nextConversation.conversation_id !== conversationId) {
      currentConversationId.value = nextConversation.conversation_id;
      viewedConversation.value = nextConversation;
      return;
    }
    const remaining = conversations.value.filter(
      (conv) => conv.conversation_id !== conversationId && !conv.parent_conversation_id,
    );
    currentConversationId.value = remaining.length > 0 ? remaining[0].conversation_id : null;
    viewedConversation.value = remaining.length > 0 ? remaining[0] : null;
  }
}

function handleConversationUnarchived(conversation: Conversation) {
  if (conversation.conversation_id === currentConversationId.value) {
    viewedConversation.value = conversation;
  }
  showActiveTrigger.value++;
}

function handleConversationRenamed(conversation: Conversation) {
  if (conversation.conversation_id === currentConversationId.value) {
    viewedConversation.value = conversation;
  }
}

async function archiveFromChat(conversationId: string) {
  await api.archiveConversation(conversationId);
  handleConversationArchived(conversationId);
}

async function archiveFromPalette(conversationId: string) {
  try {
    await api.archiveConversation(conversationId);
    handleConversationArchived(conversationId);
  } catch (err) {
    console.error("Failed to archive conversation:", err);
  }
}

function onDraftCreated(id: string) {
  currentConversationId.value = id;
}

function onCommandPaletteClose() {
  commandPaletteOpen.value = false;
  focusMessageInputIfUnfocused();
}

async function handleFirstMessage(
  message: string,
  model: string,
  cwd?: string,
  conversationType?: "normal" | "orchestrator",
  subagentBackend?: "shelley" | "claude-cli" | "codex-cli",
  toolOverrides?: Record<string, "on" | "off">,
  thinkingLevel?: "off" | "minimal" | "low" | "medium" | "high" | "xhigh",
) {
  try {
    const hasOverrides = toolOverrides && Object.keys(toolOverrides).length > 0;
    const hasThinking = !!thinkingLevel;
    const convOpts =
      conversationType === "orchestrator" || hasOverrides || hasThinking
        ? {
            ...(conversationType === "orchestrator"
              ? { type: "orchestrator" as const, subagent_backend: subagentBackend || "shelley" }
              : {}),
            ...(hasOverrides ? { tool_overrides: toolOverrides } : {}),
            ...(hasThinking ? { thinking_level: thinkingLevel } : {}),
          }
        : undefined;
    const response = await api.sendMessageWithNewConversation({
      message,
      model,
      cwd,
      conversation_options: convOpts,
    });
    const newConversationId = response.conversation_id;
    messageStore.setAgentWorking(newConversationId, true);
    currentConversationId.value = newConversationId;
  } catch (err) {
    console.error("Failed to send first message:", err);
    error.value = err instanceof Error ? err.message : "Failed to send message";
    throw err;
  }
}

async function handleDistillNewGeneration(
  sourceConversationId: string,
  model: string,
  cwd?: string,
  method?: "default" | "compact",
  instructions?: string,
) {
  try {
    await api.distillNewGeneration(sourceConversationId, model, cwd, method, instructions);
    currentConversationId.value = sourceConversationId;
  } catch (err) {
    console.error("Failed to compact into new generation:", err);
    error.value = "Failed to compact conversation";
    throw err;
  }
}

// ---- global keyboard shortcuts (incl. Ctrl+M chord) ----
let chordPending = false;
let chordTimer: number | null = null;
function clearChord() {
  chordPending = false;
  if (chordTimer !== null) {
    clearTimeout(chordTimer);
    chordTimer = null;
  }
}
const isMac = navigator.platform.toUpperCase().includes("MAC");

function handleKeyDown(e: KeyboardEvent) {
  if (chordPending) {
    clearChord();
    if (e.key === "n" || e.key === "N") {
      e.preventDefault();
      navigateToNextUserMessage();
      return;
    }
    if (e.key === "p" || e.key === "P") {
      e.preventDefault();
      navigateToPreviousUserMessage();
      return;
    }
    return;
  }

  if (e.ctrlKey && !e.metaKey && !e.altKey && (e.key === "m" || e.key === "M")) {
    e.preventDefault();
    chordPending = true;
    chordTimer = window.setTimeout(clearChord, 1500);
    return;
  }

  if (isMac && e.ctrlKey && !e.metaKey) return;
  const modifierPressed = isMac ? e.metaKey : e.ctrlKey;

  if (modifierPressed && e.key === "k") {
    e.preventDefault();
    commandPaletteOpen.value = !commandPaletteOpen.value;
    return;
  }

  if (e.altKey && !e.ctrlKey && !e.metaKey && !e.shiftKey && e.key === "ArrowDown") {
    e.preventDefault();
    navigateToNextConversation();
    return;
  }

  if (e.altKey && !e.ctrlKey && !e.metaKey && !e.shiftKey && e.key === "ArrowUp") {
    e.preventDefault();
    navigateToPreviousConversation();
    return;
  }
}

// ---- popstate (back/forward + SubagentTool navigation) ----
async function handlePopState() {
  if (isNewPath()) {
    currentConversationId.value = null;
    viewedConversation.value = null;
    return;
  }
  const slug = getSlugFromPath();
  if (!slug) return;
  const existingConv = conversations.value.find(
    (c) => c.slug === slug || c.conversation_id === slug,
  );
  if (existingConv) {
    currentConversationId.value = existingConv.conversation_id;
    viewedConversation.value = existingConv;
    return;
  }
  try {
    const conv = await api.getConversationBySlug(slug);
    if (conv) {
      currentConversationId.value = conv.conversation_id;
      viewedConversation.value = conv;
    }
  } catch (err) {
    console.error("Failed to navigate to conversation:", err);
  }
}

// ---- page title + URL sync ----
watch(
  [currentConversationId, viewedConversation, conversations],
  () => {
    const currentConv =
      viewedConversation.value?.conversation_id === currentConversationId.value
        ? viewedConversation.value
        : conversations.value.find((conv) => conv.conversation_id === currentConversationId.value);
    if (currentConv) {
      updatePageTitle(currentConv);
      updateUrlWithSlug(currentConv);
    }
  },
  { deep: false },
);

// ---- lifecycle ----
onMounted(() => {
  // Hydrate persistent terminals from the server.
  let cancelled = false;
  fetch("/api/terminals")
    .then((r) => (r.ok ? r.json() : []))
    .then((rows: Array<{ id: string; command: string; cwd: string; created_at: string }>) => {
      if (cancelled || !Array.isArray(rows) || rows.length === 0) return;
      setEphemeralTerminals((prev) => {
        const have = new Set(prev.map((tm) => tm.termId).filter(Boolean));
        const restored: EphemeralTerminal[] = rows
          .filter((r) => !have.has(r.id))
          .map((r) => ({
            id: r.id,
            termId: r.id,
            command: r.command,
            cwd: r.cwd,
            createdAt: new Date(r.created_at || Date.now()),
          }));
        return [...restored, ...prev];
      });
    })
    .catch((err) => console.warn("failed to fetch persistent terminals:", err));
  terminalsHydrationCancel = () => {
    cancelled = true;
  };

  loadConversations();

  globalStreamHandle = connectGlobalStream({
    getHash: () => conversationListHash,
    onListPatch: handleConversationListPatch,
    onNotificationEvent: handleNotificationEvent,
    onStatusChange: (status) => (streamStatus.value = status),
    onReconnect: () => {
      reconnectNonce.value++;
    },
  });

  document.addEventListener("keydown", handleKeyDown);
  window.addEventListener("popstate", handlePopState);
});

let terminalsHydrationCancel: (() => void) | null = null;

onUnmounted(() => {
  terminalsHydrationCancel?.();
  globalStreamHandle?.close();
  globalStreamHandle = null;
  document.removeEventListener("keydown", handleKeyDown);
  window.removeEventListener("popstate", handlePopState);
  clearChord();
});
</script>

// ui/src/App.tsx
import React, { useState, useEffect, useCallback, useRef } from "react";
import { WorkerPoolContextProvider } from "@pierre/diffs/react";
import type { SupportedLanguages } from "@pierre/diffs";
import ChatInterface from "./components/ChatInterface";
import type { EphemeralTerminal } from "./components/TerminalPanel";
import ConversationDrawer from "./components/ConversationDrawer";
import CommandPalette from "./components/CommandPalette";
import ModelsModal from "./components/ModelsModal";
import NotificationsModal from "./components/NotificationsModal";
import HomeFeed from "./components/HomeFeed";
import { Conversation, ConversationWithState, ConversationListUpdate } from "./types";
import { api } from "./services/api";
import { conversationCache } from "./services/conversationCache";
import { useI18n } from "./i18n";

// Worker pool configuration for @pierre/diffs syntax highlighting
// Workers run tokenization off the main thread for better performance with large diffs
const diffsPoolOptions = {
  workerFactory: () => new Worker("/diffs-worker.js"),
};

// Languages to preload in the highlighter (matches PatchTool.tsx langMap)
const diffsHighlighterOptions = {
  langs: [
    "typescript",
    "tsx",
    "javascript",
    "jsx",
    "python",
    "ruby",
    "go",
    "rust",
    "java",
    "c",
    "cpp",
    "csharp",
    "php",
    "swift",
    "kotlin",
    "scala",
    "bash",
    "sql",
    "html",
    "css",
    "scss",
    "json",
    "xml",
    "yaml",
    "toml",
    "markdown",
  ] as SupportedLanguages[],
};

// Check if a slug is a generated ID (format: cXXXX where X is alphanumeric)
function isGeneratedId(slug: string | null): boolean {
  if (!slug) return true;
  return /^c[a-z0-9]+$/i.test(slug);
}

// Get slug from the current URL path (expects /c/<slug> format)
function getSlugFromPath(): string | null {
  const path = window.location.pathname;
  // Check for /c/<slug> format
  if (path.startsWith("/c/")) {
    const slug = path.slice(3); // Remove "/c/" prefix
    if (slug) {
      return slug;
    }
  }
  return null;
}

function isInboxPath(): boolean {
  return window.location.pathname === "/inbox";
}

function isNewPath(): boolean {
  return window.location.pathname === "/new";
}

// Capture the initial slug from URL BEFORE React renders, so it won't be affected
// by the useEffect that updates the URL based on current conversation.
const initialSlugFromUrl = getSlugFromPath();
const initialIsInbox = isInboxPath();
const initialIsNew = isNewPath();

// Update the URL to reflect the current conversation slug
function updateUrlWithSlug(conversation: Conversation | undefined) {
  const currentSlug = getSlugFromPath();
  const newSlug =
    conversation?.slug && !isGeneratedId(conversation.slug) ? conversation.slug : null;

  if (currentSlug !== newSlug) {
    if (newSlug) {
      window.history.replaceState({}, "", `/c/${newSlug}`);
    } else {
      window.history.replaceState({}, "", "/");
    }
  }
}

function updatePageTitle(conversation: Conversation | undefined) {
  const hostname = window.__SHELLEY_INIT__?.hostname;
  const parts: string[] = [];

  if (conversation?.slug && !isGeneratedId(conversation.slug)) {
    parts.push(conversation.slug);
  }
  if (hostname) {
    parts.push(hostname);
  }
  parts.push("Shelley Agent");

  document.title = parts.join(" - ");
}

function App() {
  const { t } = useI18n();
  const [conversations, setConversations] = useState<ConversationWithState[]>([]);
  const [currentConversationId, setCurrentConversationId] = useState<string | null>(null);
  // Track viewed conversation separately (needed for subagents which aren't in main list)
  const [viewedConversation, setViewedConversation] = useState<Conversation | null>(null);
  const [showInbox, setShowInbox] = useState(initialIsInbox);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [drawerCollapsed, setDrawerCollapsed] = useState(false);
  const [commandPaletteOpen, setCommandPaletteOpen] = useState(false);
  const [diffViewerTrigger, setDiffViewerTrigger] = useState(0);
  const [modelsModalOpen, setModelsModalOpen] = useState(false);
  const [notificationsModalOpen, setNotificationsModalOpen] = useState(false);
  const [modelsRefreshTrigger, setModelsRefreshTrigger] = useState(0);
  const [navigateUserMessageTrigger, setNavigateUserMessageTrigger] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  // Global ephemeral terminals - persist across conversation switches
  const [ephemeralTerminals, setEphemeralTerminals] = useState<EphemeralTerminal[]>([]);
  const [subagentUpdate, setSubagentUpdate] = useState<Conversation | null>(null);
  const [showActiveTrigger, setShowActiveTrigger] = useState(0);
  const [subagentStateUpdate, setSubagentStateUpdate] = useState<{
    conversation_id: string;
    working: boolean;
  } | null>(null);
  const initialSlugResolved = useRef(false);

  // Resolve initial slug from URL - uses the captured initialSlugFromUrl
  // Returns the conversation if found, null otherwise
  const resolveInitialSlug = useCallback(
    async (convs: Conversation[]): Promise<Conversation | null> => {
      if (initialSlugResolved.current) return null;
      initialSlugResolved.current = true;

      const urlSlug = initialSlugFromUrl;
      if (!urlSlug) return null;

      // First check if we already have this conversation in our list
      const existingConv = convs.find((c) => c.slug === urlSlug);
      if (existingConv) return existingConv;

      // Otherwise, try to fetch by slug (may be a subagent)
      try {
        const conv = await api.getConversationBySlug(urlSlug);
        if (conv) return conv;
      } catch (err) {
        console.error("Failed to resolve slug:", err);
      }

      // Slug not found, clear the URL
      window.history.replaceState({}, "", "/");
      return null;
    },
    [],
  );

  // Load conversations on mount
  useEffect(() => {
    loadConversations();
  }, []);

  const navigateToNextConversation = useCallback(() => {
    if (conversations.length === 0) return;
    const currentIndex = conversations.findIndex(
      (c) => c.conversation_id === currentConversationId,
    );
    // Next = further down the list (older)
    const nextIndex = currentIndex < 0 ? 0 : Math.min(currentIndex + 1, conversations.length - 1);
    const next = conversations[nextIndex];
    setCurrentConversationId(next.conversation_id);
    setViewedConversation(next);
  }, [conversations, currentConversationId]);

  const navigateToPreviousConversation = useCallback(() => {
    if (conversations.length === 0) return;
    const currentIndex = conversations.findIndex(
      (c) => c.conversation_id === currentConversationId,
    );
    // Previous = further up the list (newer)
    const prevIndex = currentIndex < 0 ? 0 : Math.max(currentIndex - 1, 0);
    const prev = conversations[prevIndex];
    setCurrentConversationId(prev.conversation_id);
    setViewedConversation(prev);
  }, [conversations, currentConversationId]);

  const navigateToNextUserMessage = useCallback(() => {
    setNavigateUserMessageTrigger((prev) => Math.abs(prev) + 1);
  }, []);

  const navigateToPreviousUserMessage = useCallback(() => {
    setNavigateUserMessageTrigger((prev) => -(Math.abs(prev) + 1));
  }, []);

  // Global keyboard shortcuts (including Ctrl+M chord sequences)
  useEffect(() => {
    const isMac = navigator.platform.toUpperCase().includes("MAC");
    let chordPending = false;
    let chordTimer: number | null = null;

    const clearChord = () => {
      chordPending = false;
      if (chordTimer !== null) {
        clearTimeout(chordTimer);
        chordTimer = null;
      }
    };

    const handleKeyDown = (e: KeyboardEvent) => {
      // Handle second key of Ctrl+M chord (before the Mac Ctrl passthrough)
      if (chordPending) {
        clearChord();
        if (e.key === "n" || e.key === "N") {
          e.preventDefault();
          navigateToNextUserMessage();
          return;
        }
        if (e.key === "p" || e.key === "P") {
          e.preventDefault();
          navigateToPreviousUserMessage();
          return;
        }
        // Any other key cancels the chord
        return;
      }

      // Ctrl+M on all platforms: start chord sequence
      // (intentionally before the Mac Ctrl passthrough — we use Ctrl, not Cmd,
      // to avoid overriding Cmd+M which is system minimize on macOS)
      if (e.ctrlKey && !e.metaKey && !e.altKey && (e.key === "m" || e.key === "M")) {
        e.preventDefault();
        chordPending = true;
        // Auto-cancel chord after 1.5 seconds
        chordTimer = window.setTimeout(clearChord, 1500);
        return;
      }

      // On macOS: Ctrl+K is readline (kill to end of line), let it pass through
      if (isMac && e.ctrlKey && !e.metaKey) return;
      // On macOS use Cmd+K, on other platforms use Ctrl+K
      const modifierPressed = isMac ? e.metaKey : e.ctrlKey;

      if (modifierPressed && e.key === "k") {
        e.preventDefault();
        setCommandPaletteOpen((prev) => !prev);
        return;
      }

      // Alt+ArrowDown: next conversation
      if (e.altKey && !e.ctrlKey && !e.metaKey && !e.shiftKey && e.key === "ArrowDown") {
        e.preventDefault();
        navigateToNextConversation();
        return;
      }

      // Alt+ArrowUp: previous conversation
      if (e.altKey && !e.ctrlKey && !e.metaKey && !e.shiftKey && e.key === "ArrowUp") {
        e.preventDefault();
        navigateToPreviousConversation();
        return;
      }
    };
    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      clearChord();
    };
  }, [
    navigateToNextConversation,
    navigateToPreviousConversation,
    navigateToNextUserMessage,
    navigateToPreviousUserMessage,
  ]);

  // Handle popstate events (browser back/forward and SubagentTool navigation)
  useEffect(() => {
    const handlePopState = async () => {
      if (isInboxPath()) {
        setShowInbox(true);
        setCurrentConversationId(null);
        setViewedConversation(null);
        return;
      }
      if (isNewPath()) {
        setShowInbox(false);
        setCurrentConversationId(null);
        setViewedConversation(null);
        return;
      }
      setShowInbox(false);
      const slug = getSlugFromPath();
      if (!slug) {
        return;
      }

      // Try to find in existing conversations first
      const existingConv = conversations.find((c) => c.slug === slug);
      if (existingConv) {
        setCurrentConversationId(existingConv.conversation_id);
        setViewedConversation(existingConv);
        return;
      }

      // Otherwise fetch by slug (may be a subagent)
      try {
        const conv = await api.getConversationBySlug(slug);
        if (conv) {
          setCurrentConversationId(conv.conversation_id);
          setViewedConversation(conv);
        }
      } catch (err) {
        console.error("Failed to navigate to conversation:", err);
      }
    };

    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, [conversations]);

  // Handle conversation list updates from the message stream
  const handleConversationListUpdate = useCallback((update: ConversationListUpdate) => {
    if (update.type === "update" && update.conversation) {
      // Handle subagent conversations separately
      if (update.conversation.parent_conversation_id) {
        setSubagentUpdate(update.conversation);
        return;
      }

      // If the conversation is archived, remove it from the active list
      if (update.conversation.archived) {
        setConversations((prev) =>
          prev.filter((c) => c.conversation_id !== update.conversation!.conversation_id),
        );
        return;
      }

      setConversations((prev) => {
        // Check if this conversation already exists
        const existingIndex = prev.findIndex(
          (c) => c.conversation_id === update.conversation!.conversation_id,
        );

        const gitFields = {
          git_repo_root: update.git_repo_root,
          git_worktree_root: update.git_worktree_root,
          pr_info: update.pr_info,
        };
        if (existingIndex >= 0) {
          // Update existing conversation in place, preserving working state and git info
          // (working state is updated separately via conversation_state)
          const updated = [...prev];
          updated[existingIndex] = {
            ...update.conversation!,
            ...gitFields,
            working: prev[existingIndex].working,
            git_commit: prev[existingIndex].git_commit,
            git_subject: prev[existingIndex].git_subject,
            subagent_count: prev[existingIndex].subagent_count,
          };
          return updated;
        } else {
          // Add new conversation at the top (not working by default)
          return [
            { ...update.conversation!, ...gitFields, working: false, subagent_count: 0 },
            ...prev,
          ];
        }
      });
    } else if (update.type === "delete" && update.conversation_id) {
      setConversations((prev) => prev.filter((c) => c.conversation_id !== update.conversation_id));
      conversationCache.delete(update.conversation_id);
    }
  }, []);

  // Handle conversation state updates (working state changes)
  const handleConversationStateUpdate = useCallback(
    (state: { conversation_id: string; working: boolean }) => {
      // Check if this is a top-level conversation
      setConversations((prev) => {
        const found = prev.find((conv) => conv.conversation_id === state.conversation_id);
        if (found) {
          return prev.map((conv) =>
            conv.conversation_id === state.conversation_id
              ? { ...conv, working: state.working }
              : conv,
          );
        }
        // Not a top-level conversation, might be a subagent
        // Pass the state update to the drawer
        setSubagentStateUpdate(state);
        return prev;
      });
    },
    [],
  );

  // Update page title and URL when conversation changes
  useEffect(() => {
    // Use viewedConversation if it matches (handles subagents), otherwise look up from list
    const currentConv =
      viewedConversation?.conversation_id === currentConversationId
        ? viewedConversation
        : conversations.find((conv) => conv.conversation_id === currentConversationId);
    if (currentConv) {
      updatePageTitle(currentConv);
      updateUrlWithSlug(currentConv);
    }
  }, [currentConversationId, viewedConversation, conversations]);

  const loadConversations = async () => {
    try {
      setLoading(true);
      setError(null);
      const convs = await api.getConversations();
      setConversations(convs);

      // Try to resolve conversation from URL slug first
      const slugConv = await resolveInitialSlug(convs);
      if (slugConv) {
        setCurrentConversationId(slugConv.conversation_id);
        setViewedConversation(slugConv);
      } else if (!showInbox && !initialIsNew && convs.length > 0) {
        // No slug in URL and not on /inbox or /new — select the most recent conversation
        setCurrentConversationId(convs[0].conversation_id);
        setViewedConversation(convs[0]);
      }
    } catch (err) {
      console.error("Failed to load conversations:", err);
      setError("Failed to load conversations. Please refresh the page.");
    } finally {
      setLoading(false);
    }
  };

  const refreshConversations = async () => {
    try {
      const convs = await api.getConversations();
      setConversations(convs);
    } catch (err) {
      console.error("Failed to refresh conversations:", err);
    }
  };

  const startNewConversation = () => {
    // Save the current conversation's cwd to localStorage so the new conversation picks it up
    if (currentConversation?.cwd) {
      localStorage.setItem("shelley_selected_cwd", currentConversation.cwd);
    }
    // Clear the current conversation - a new one will be created when the user sends their first message
    setCurrentConversationId(null);
    setViewedConversation(null);
    // Clear URL when starting new conversation
    window.history.replaceState({}, "", "/");
    setDrawerOpen(false);
  };

  const startNewConversationWithCwd = (cwd: string) => {
    localStorage.setItem("shelley_selected_cwd", cwd);
    setCurrentConversationId(null);
    setViewedConversation(null);
    window.history.replaceState({}, "", "/");
    setDrawerOpen(false);
  };

  const selectConversation = (conversation: Conversation) => {
    const wasOnInbox = showInbox;
    setCurrentConversationId(conversation.conversation_id);
    setViewedConversation(conversation);
    setShowInbox(false);
    setDrawerOpen(false);
    // Use pushState when navigating from inbox so back button returns there
    if (wasOnInbox) {
      const slug =
        conversation.slug && !isGeneratedId(conversation.slug) ? conversation.slug : null;
      if (slug) {
        window.history.pushState({}, "", `/c/${slug}`);
      }
    }
  };

  const toggleDrawerCollapsed = () => {
    setDrawerCollapsed((prev) => !prev);
  };

  const updateConversation = (updatedConversation: Conversation) => {
    // Skip subagent conversations for the main list
    if (updatedConversation.parent_conversation_id) {
      return;
    }
    setConversations((prev) =>
      prev.map((conv) =>
        conv.conversation_id === updatedConversation.conversation_id
          ? {
              ...updatedConversation,
              // Preserve list-level state fields maintained elsewhere
              working: conv.working,
              subagent_count: conv.subagent_count,
              // Preserve git metadata from conversation list updates.
              // Stream conversation updates don't include these fields.
              git_repo_root: conv.git_repo_root,
              git_worktree_root: conv.git_worktree_root,
              git_commit: conv.git_commit,
              git_subject: conv.git_subject,
              pr_info: conv.pr_info,
            }
          : conv,
      ),
    );
  };

  const handleConversationArchived = (conversationId: string) => {
    setConversations((prev) => prev.filter((conv) => conv.conversation_id !== conversationId));
    conversationCache.delete(conversationId);
    // If the archived conversation was current, switch to another or clear
    if (currentConversationId === conversationId) {
      const remaining = conversations.filter((conv) => conv.conversation_id !== conversationId);
      setCurrentConversationId(remaining.length > 0 ? remaining[0].conversation_id : null);
    }
  };

  const handleConversationUnarchived = (conversation: Conversation) => {
    // Add back to active list if not already present (SSE may also deliver this).
    // We need this handler in case no SSE connection is active (e.g., when all
    // conversations are archived). If SSE also delivers the update,
    // handleConversationListUpdate will find it already present and update in-place.
    setConversations((prev) =>
      prev.some((c) => c.conversation_id === conversation.conversation_id)
        ? prev
        : [{ ...conversation, working: false, subagent_count: 0 }, ...prev],
    );
    // Update viewedConversation so archived state reflects immediately
    if (conversation.conversation_id === currentConversationId) {
      setViewedConversation(conversation);
    }
    // Switch drawer back to active conversations view
    setShowActiveTrigger((prev) => prev + 1);
  };

  const handleConversationRenamed = (conversation: Conversation) => {
    // Update the conversation in the list with the new slug, preserving working/git state
    setConversations((prev) =>
      prev.map((c) =>
        c.conversation_id === conversation.conversation_id
          ? {
              ...conversation,
              working: c.working,
              git_commit: c.git_commit,
              git_subject: c.git_subject,
              subagent_count: c.subagent_count,
              pr_info: c.pr_info,
            }
          : c,
      ),
    );
  };

  if (loading && conversations.length === 0) {
    return (
      <div className="loading-container">
        <div className="loading-content">
          <div className="spinner" style={{ margin: "0 auto 1rem" }}></div>
          <p className="text-secondary">{t("loading")}</p>
        </div>
      </div>
    );
  }

  if (error && conversations.length === 0) {
    return (
      <div className="error-container">
        <div className="error-content">
          <p className="error-message" style={{ marginBottom: "1rem" }}>
            {error}
          </p>
          <button onClick={loadConversations} className="btn-primary">
            {t("retry")}
          </button>
        </div>
      </div>
    );
  }

  const currentConversation =
    conversations.find((conv) => conv.conversation_id === currentConversationId) ||
    (viewedConversation?.conversation_id === currentConversationId
      ? { ...viewedConversation, working: false, subagent_count: 0 }
      : undefined);

  // Get the CWD from the current conversation, or fall back to the most recent conversation
  const mostRecentCwd =
    currentConversation?.cwd || (conversations.length > 0 ? conversations[0].cwd : null);

  const handleFirstMessage = async (
    message: string,
    model: string,
    cwd?: string,
    conversationType?: "normal" | "orchestrator",
    subagentBackend?: "shelley" | "claude-cli" | "codex-cli",
  ) => {
    try {
      const response = await api.sendMessageWithNewConversation({
        message,
        model,
        cwd,
        conversation_options:
          conversationType === "orchestrator"
            ? { type: "orchestrator", subagent_backend: subagentBackend || "shelley" }
            : undefined,
      });
      const newConversationId = response.conversation_id;

      // Fetch the new conversation details
      const updatedConvs = await api.getConversations();
      setConversations(updatedConvs);
      setShowInbox(false);
      setCurrentConversationId(newConversationId);
    } catch (err) {
      console.error("Failed to send first message:", err);
      setError("Failed to send message");
      throw err;
    }
  };

  const handleDistillConversation = async (
    sourceConversationId: string,
    model: string,
    cwd?: string,
  ) => {
    try {
      const response = await api.distillConversation(sourceConversationId, model, cwd);
      const newConversationId = response.conversation_id;

      // Fetch the new conversation details and switch to the new conversation
      const updatedConvs = await api.getConversations();
      setConversations(updatedConvs);
      setCurrentConversationId(newConversationId);
    } catch (err) {
      console.error("Failed to distill conversation:", err);
      setError("Failed to distill conversation");
      throw err;
    }
  };

  const handleDistillReplaceConversation = async (
    sourceConversationId: string,
    model: string,
    cwd?: string,
  ) => {
    try {
      const response = await api.distillReplaceConversation(sourceConversationId, model, cwd);
      const newConversationId = response.conversation_id;
      const updatedConvs = await api.getConversations();
      setConversations(updatedConvs);
      setCurrentConversationId(newConversationId);
    } catch (err) {
      console.error("Failed to distill-replace conversation:", err);
      setError("Failed to distill-replace conversation");
      throw err;
    }
  };

  return (
    <WorkerPoolContextProvider
      poolOptions={diffsPoolOptions}
      highlighterOptions={diffsHighlighterOptions}
    >
      <div className="app-container">
        {/* Conversations drawer - hidden on inbox */}
        <ConversationDrawer
          isOpen={drawerOpen}
          isCollapsed={showInbox || drawerCollapsed}
          onClose={() => setDrawerOpen(false)}
          onToggleCollapse={toggleDrawerCollapsed}
          conversations={conversations}
          currentConversationId={currentConversationId}
          viewedConversation={viewedConversation}
          onSelectConversation={selectConversation}
          onNewConversation={startNewConversation}
          onConversationArchived={handleConversationArchived}
          onConversationUnarchived={handleConversationUnarchived}
          onConversationRenamed={handleConversationRenamed}
          subagentUpdate={subagentUpdate}
          subagentStateUpdate={subagentStateUpdate}
          showActiveTrigger={showActiveTrigger}
        />

        {/* Main content: Home feed or Chat interface */}
        <div className="main-content">
          {showInbox ? (
            <HomeFeed
              conversations={conversations}
              onSelectConversation={selectConversation}
              onNewConversation={startNewConversation}
              onArchiveConversation={async (conversationId: string) => {
                await api.archiveConversation(conversationId);
                handleConversationArchived(conversationId);
              }}
              onFirstMessage={handleFirstMessage}
              onReplyToConversation={async (conversationId: string, message: string) => {
                // Send the reply and stay on inbox
                try {
                  await api.sendMessage(conversationId, { message });
                } catch (err) {
                  console.error("Failed to send reply:", err);
                }
              }}
              mostRecentCwd={mostRecentCwd}
              onOpenModelsModal={() => setModelsModalOpen(true)}
              onOpenDrawer={() => setDrawerOpen(true)}
              models={window.__SHELLEY_INIT__?.models || []}
              defaultModel={window.__SHELLEY_INIT__?.default_model || ""}
              hostname={window.__SHELLEY_INIT__?.hostname || "localhost"}
            />
          ) : (
            <ChatInterface
              conversationId={currentConversationId}
              onOpenDrawer={() => setDrawerOpen(true)}
              onNewConversation={startNewConversation}
              onArchiveConversation={async (conversationId: string) => {
                await api.archiveConversation(conversationId);
                handleConversationArchived(conversationId);
              }}
              currentConversation={currentConversation}
              onConversationUpdate={updateConversation}
              onConversationListUpdate={handleConversationListUpdate}
              onConversationStateUpdate={handleConversationStateUpdate}
              onFirstMessage={handleFirstMessage}
              onDistillConversation={handleDistillConversation}
              onDistillReplaceConversation={handleDistillReplaceConversation}
              mostRecentCwd={mostRecentCwd}
              isDrawerCollapsed={drawerCollapsed}
              onToggleDrawerCollapse={toggleDrawerCollapsed}
              openDiffViewerTrigger={diffViewerTrigger}
              modelsRefreshTrigger={modelsRefreshTrigger}
              onOpenModelsModal={() => setModelsModalOpen(true)}
              onReconnect={refreshConversations}
              ephemeralTerminals={ephemeralTerminals}
              setEphemeralTerminals={setEphemeralTerminals}
              navigateUserMessageTrigger={navigateUserMessageTrigger}
              onConversationUnarchived={handleConversationUnarchived}
            />
          )}
        </div>

        {/* Command Palette */}
        <CommandPalette
          isOpen={commandPaletteOpen}
          onClose={() => setCommandPaletteOpen(false)}
          conversations={conversations}
          currentConversation={currentConversation || null}
          onNewConversation={() => {
            startNewConversation();
            setCommandPaletteOpen(false);
          }}
          onNewConversationWithCwd={(cwd: string) => {
            startNewConversationWithCwd(cwd);
            setCommandPaletteOpen(false);
          }}
          onSelectConversation={(conversation) => {
            selectConversation(conversation);
            setCommandPaletteOpen(false);
          }}
          onArchiveConversation={async (conversationId: string) => {
            try {
              await api.archiveConversation(conversationId);
              handleConversationArchived(conversationId);
            } catch (err) {
              console.error("Failed to archive conversation:", err);
            }
          }}
          onOpenDiffViewer={() => {
            setDiffViewerTrigger((prev) => prev + 1);
            setCommandPaletteOpen(false);
          }}
          onOpenModelsModal={() => {
            setModelsModalOpen(true);
            setCommandPaletteOpen(false);
          }}
          onOpenNotificationsModal={() => {
            setNotificationsModalOpen(true);
            setCommandPaletteOpen(false);
          }}
          onNextConversation={navigateToNextConversation}
          onPreviousConversation={navigateToPreviousConversation}
          onNextUserMessage={navigateToNextUserMessage}
          onPreviousUserMessage={navigateToPreviousUserMessage}
          hasCwd={!!(currentConversation?.cwd || mostRecentCwd)}
        />

        <ModelsModal
          isOpen={modelsModalOpen}
          onClose={() => setModelsModalOpen(false)}
          onModelsChanged={() => setModelsRefreshTrigger((prev) => prev + 1)}
        />

        <NotificationsModal
          isOpen={notificationsModalOpen}
          onClose={() => setNotificationsModalOpen(false)}
        />

        {/* Backdrop for mobile drawer */}
        {drawerOpen && (
          <div className="backdrop hide-on-desktop" onClick={() => setDrawerOpen(false)} />
        )}
      </div>
    </WorkerPoolContextProvider>
  );
}

export default App;
