// ui/src/components/UserCommandsList.tsx
import React, { useEffect, useState } from "react";
import { api, SlashUserCommand } from "../services/api";
import CommandViewerModal from "./CommandViewerModal";

interface UserCommandsListProps {
  cwd?: string;
}

function UserCommandsList({ cwd }: UserCommandsListProps) {
  const [commands, setCommands] = useState<SlashUserCommand[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [viewing, setViewing] = useState<SlashUserCommand | null>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    api
      .getSlashCommands(cwd)
      .then((d) => {
        if (!cancelled) {
          setCommands([...d.user_commands].sort((a, b) => a.name.localeCompare(b.name)));
          setError(null);
        }
      })
      .catch((err) => {
        if (!cancelled) setError(err.message || String(err));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [cwd]);

  if (loading) {
    return <div className="drawer-empty-state text-secondary"><p>Loading…</p></div>;
  }
  if (error) {
    return <div className="drawer-empty-state text-secondary"><p>Failed: {error}</p></div>;
  }
  if (commands.length === 0) {
    return (
      <div className="drawer-empty-state text-secondary">
        <p>No user-defined commands found.</p>
        <p className="skills-list-hint">
          Drop a markdown file into <code>~/.claude/commands/</code> or <code>.claude/commands/</code>.
        </p>
      </div>
    );
  }

  return (
    <>
      <ul className="skills-list">
        {commands.map((c) => (
          <li key={c.path}>
            <button type="button" className="skills-list-item" onClick={() => setViewing(c)}>
              <span className="skills-list-name">/{c.name}</span>
              <span className="skills-list-desc">{c.description || c.path}</span>
              <span className={`skills-list-scope skills-list-scope-${c.scope}`}>{c.scope}</span>
            </button>
          </li>
        ))}
      </ul>
      {viewing && (
        <CommandViewerModal command={viewing} onClose={() => setViewing(null)} />
      )}
    </>
  );
}

export default UserCommandsList;

// ui/src/vue/components/UserCommandsList.vue
<!-- Library > Commands tab. Lists user-defined slash commands from
     /api/commands (user_commands); clicking one opens its detail in
     CommandViewerModal. Vue port of components/UserCommandsList.tsx. -->
<template>
  <div v-if="loading" class="drawer-empty-state text-secondary">
    <p>{{ t("loading") }}</p>
  </div>
  <div v-else-if="error" class="drawer-empty-state text-secondary">
    <p>{{ t("failedToLoad") }}: {{ error }}</p>
  </div>
  <div v-else-if="commands.length === 0" class="drawer-empty-state text-secondary">
    <p>{{ t("noUserCommands") }}</p>
    <p class="skills-list-hint">
      {{ t("commandsListHint") }}
    </p>
  </div>
  <template v-else>
    <ul class="skills-list">
      <li v-for="c in commands" :key="`${c.scope}:${c.name}`">
        <button type="button" class="skills-list-item" @click="viewing = c">
          <span class="skills-list-name">/{{ c.name }}</span>
          <span class="skills-list-desc">{{ c.description || c.path }}</span>
          <span :class="`skills-list-scope skills-list-scope-${c.scope}`">{{ c.scope }}</span>
        </button>
      </li>
    </ul>
    <CommandViewerModal v-if="viewing" :command="viewing" @close="viewing = null" />
  </template>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { api, type SlashUserCommand } from "../../services/api";
import { useI18n } from "../composables/i18n";
import CommandViewerModal from "./CommandViewerModal.vue";

const props = defineProps<{ cwd?: string }>();

const { t } = useI18n();
const commands = ref<SlashUserCommand[]>([]);
const loading = ref(true);
const error = ref<string | null>(null);
const viewing = ref<SlashUserCommand | null>(null);

onMounted(async () => {
  try {
    const data = await api.getCommands(props.cwd);
    commands.value = [...data.user_commands].sort((a, b) => a.name.localeCompare(b.name));
    error.value = null;
  } catch (err) {
    error.value = err instanceof Error ? err.message : String(err);
  } finally {
    loading.value = false;
  }
});
</script>
