// ui/src/vue/components/CommandViewerModal.vue
<!-- Read-only viewer for a Library user command. The command payload (body,
     description, argument-hint) already comes from /api/commands, so no extra
     fetch is needed. Vue port of components/CommandViewerModal.tsx. -->
<template>
  <Modal
    :is-open="true"
    :title="`/${command.name}`"
    class-name="skill-viewer-modal"
    @close="emit('close')"
  >
    <p class="skill-viewer-path" :title="command.path">{{ command.path }}</p>
    <p v-if="command.description" class="command-viewer-description">
      {{ command.description }}
    </p>
    <p v-if="command.argument_hint" class="command-viewer-hint">
      <strong>{{ t("argumentHint") }}:</strong> <code>{{ command.argument_hint }}</code>
    </p>
    <div class="skill-viewer-content">
      <MarkdownContent :text="command.body" />
    </div>
  </Modal>
</template>

<script setup lang="ts">
import Modal from "./Modal.vue";
import MarkdownContent from "./MarkdownContent.vue";
import type { SlashUserCommand } from "../../services/api";
import { useI18n } from "../composables/i18n";

defineProps<{ command: SlashUserCommand }>();
const emit = defineEmits<{ (e: "close"): void }>();

const { t } = useI18n();
</script>

// ui/src/components/CommandViewerModal.tsx
import React from "react";
import Modal from "./Modal";
import MarkdownContent from "./MarkdownContent";
import { SlashUserCommand } from "../services/api";

interface CommandViewerModalProps {
  command: SlashUserCommand;
  onClose: () => void;
}

function CommandViewerModal({ command, onClose }: CommandViewerModalProps) {
  return (
    <Modal isOpen onClose={onClose} title={`/${command.name}`} className="skill-viewer-modal">
      <p className="skill-viewer-path" title={command.path}>{command.path}</p>
      {command.description && (
        <p className="command-viewer-description">{command.description}</p>
      )}
      {command.argument_hint && (
        <p className="command-viewer-hint"><strong>Argument hint:</strong> <code>{command.argument_hint}</code></p>
      )}
      <div className="skill-viewer-content">
        <MarkdownContent text={command.body} />
      </div>
    </Modal>
  );
}

export default CommandViewerModal;
